### ISSUE TITLE
Multiple APNS certificates for different apps

### ISSUE THREAD

**Issue by afonsograca** [amyth/django-push#1]
Hi there,

First of all, thank you for your effort to bring Notifications to mongoengine Django projects. 
My backend has to support two distinct apps (i.e. client's app and employee's app) and push notifications to both.

Is there a way to register multiple .pem files in order to serve different apps?

Cheers.

**Comment by amyth** [comment]
You can pass your `.pem` file  as keyword `certfile` to the methods `apns_send_bulk_message` and `apns_send_message`. So you can extend the `APNSDevice` model and add custom methods for `employee` and `client` and pass `certfile` in keyword arguments. For example:

```
from django.conf import settings
from instapush.models.mongo import APNSDevice

class CustomAPNSDevice(APNSDevice):
    def client_send_apns(self, message):
        self.send_message(message, **{certfile: settings.CLIENT_APNS_CERTIFICATE})

    def employee_send_apns(self, message):
        self.send_message(message, **{certfile: settings.EMPLOYEE_APNS_CERTIFICATE})
```

and then use these methods to send the messages.

**Comment by afonsograca** [comment]
Cool. Thanks for your detailed reply.

Cheers.
